<script type="text/javascript">
$(document).ready(function(){

    var landlords_table = $('table#landlords_table').dataTable();

    $.ajax({
      url: '<?=  $this->url->get("superadmin/landlord/viewlandlords") ?>',
      dataType: 'json',
      success: function(data)
      {
         //console.log(data);

        
        landlords_table.fnClearTable();
        for(var i = 0; i < data.length; i++) { 
          landlords_table.fnAddData([ 
            data[i][0], 
            data[i][1], 
            data[i][2], 
            data[i][3],
            data[i][4],
            data[i][5],
            data[i][6],
            data[i][7]

          ]); 
        } // End For
        // data;

         }

    });

	function notify(from, align, icon, type, animIn, animOut, msg){
    $.growl({
        icon: icon,
        title: 'Saved. ',
        message: msg,
        url: ''
    },{
            element: 'body',
            type: type,
            allow_dismiss: true,
            placement: {
                    from: from,
                    align: align
            },
            offset: {
                x: 20,
                y: 85
            },
            spacing: 10,
            z_index: 1031,
            delay: 2500,
            timer: 1000,
            url_target: '_blank',
            mouse_over: false,
            animate: {
                    enter: animIn,
                    exit: animOut
            },
            icon_type: 'class',
            template: '<div data-growl="container" class="alert" role="alert">' +
                            '<button type="button" class="close" data-growl="dismiss">' +
                                '<span aria-hidden="true">&times;</span>' +
                                '<span class="sr-only">Close</span>' +
                            '</button>' +
                            '<span data-growl="icon"></span>' +
                            '<span data-growl="title"></span>' +
                            '<span data-growl="message"></span>' +
                            '<a href="#" data-growl="url"></a>' +
                        '</div>'
    });
};

	var landlordadded_json = '<?= $landlordadded_json;?>';
    console.log(landlordadded_json);

    

    if(landlordadded_json !="")
    {
    	obj = jQuery.parseJSON(landlordadded_json);
    	console.log(obj.type);
     	notify(obj.type, "", "", "", "", "", obj.message);
    }


});


</script>